Error while okconfg init
while doing " okconfig init " I got an error 

Initilizating nagios to use okconfig...
Error: 'module' object has no attribute 'Config'

I made a change in code /usr/local/bin/okconfig line 204, I changed  

maincfg = pynag.Parsers.Config().guess_cfg_file()  
maincfg = pynag.Parsers.config().guess_cfg_file()

just a little change of capital "C"